#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import argparse
import schirmclient as schirm

html = """
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<style>
#editor {
        position: relative;
        width: 100%%;
        height: 400px;
}
</style>
</head>
<body>
    <div id="editor">%(text)s</div>
    <script src="src/ace.js" type="text/javascript" charset="utf-8"></script>
    <script src="src/theme-clouds.js" type="text/javascript" charset="utf-8"></script>
    <script>
    window.onload = function() {
        //var editor = ace.edit("editor");
        //editor.setTheme("ace/theme/clouds");
        window.location="/"
        //schirmlog();
    };
    </script>
</body>
</html>
"""

css = """
@font-face {
  font-family: 'Droid Sans Mono';
  font-style: normal;
  font-weight: normal;
  src: local('Droid Sans Mono'), local('DroidSansMono'), format('woff');
}
"""

def main():
    with schirm.frame():
        schirm.register_resource(os.path.join(os.path.abspath(os.path.dirname(__file__)),'../misc/ace.js'), 'src/ace.js')
        schirm.register_resource(os.path.join(os.path.abspath(os.path.dirname(__file__)),'../misc/theme-clouds.js'), 'src/theme-clouds.js')
        schirm.register_resource_data(html % {'text':"some text"}, 'editor.html')
        print html % {'text':"some text"}
        schirm.close()
        req = schirm.read_next()
        if req.type == 'request':
            # fake the googleapi response
            if req.method == 'GET' and req.path.startswith('http://fonts.googleapis.com/css'):
                schirm.respond(req.id, '\r\n'.join((req.protocol + " 200 OK", "Cache-Control: no-cache", "Content-Type: text/css", "", css)))
            x = schirm.read_next()

    print 'bye'
    print x

if __name__ == '__main__':
    print main()
