#!/usr/bin/env python

import os
import sys
import schirmclient as schirm

def view_file(fname):
    with schirm.frame(width='100%'):
        schirm.register_resource(fname, 'x')
        print '<div style="overflow:visible"> <img style="width:100%;" src="x"></div>'

if __name__ == '__main__':

    if len(sys.argv) == 2:
        filename = sys.argv[1]
        if os.path.exists(filename):
            view_file(sys.argv[1])
        else:
            print "{} does not exist".format(filename)
    else:
        print "Usage: gaze IMAGE-FILENAME"
